### ISSUE TITLE
[API] Update payments route to query a range of time

### ISSUE THREAD

**Issue by pacna** [HackRVA/memberdashboard#157]
Update `/api/payments/charts` route to take a range of time. Probably `startDate` and `endDate` query params

**Comment by dfirebaugh** [comment]
we should update this so the routes make more sense.

e.g.
we should have a route for `/api/report/member-distribution-chart` (if it's returning the json in a format that the chart wants)

actually, I was thinking we should just respond with data that represents the stats and have a chart generation function that formats how the chart wants it.  so, the routes would be nicer.
... like `/api/stats/member-distribution` or something like that. 
Which might return something like
```json
{
    "2020-03": {
        "classic": 12,
        "standard": 59,
        "premium": 12,
        "credited": 5
    },
    "2020-04": {
        "classic": 12,
        "standard": 59,
        "premium": 12,
        "credited": 5
    },
    "2020-05": {
        "classic": 12,
        "standard": 120,
        "premium": 12,
        "credited": 5
    }
}
```

You could then use the builder pattern to create charts

**Comment by dfirebaugh** [comment]
we no longer have payments since things are based on subscriptionID instead
