### ISSUE TITLE
Triple Dot dropdown options in the member list do not map to the member visible in that row after the visible member changes

### ISSUE THREAD

**Issue by warasilapm** [HackRVA/memberdashboard#179]
Browser: Chrome Version 121.0.6167.185 (Official Build) (64-bit)

On the members tab, when I search for a member and then use this drop down to perform an action, it is applied to the member that was visible in the row when first populated with the entire member list.

I attempted to scroll through the members to work around this issue. However, the accounting is still a few rows behind for some reason.

**Comment by warasilapm** [comment]
I encountered this while trying to add the `frontdoor` resource back to Grey. The issue only appears to occur while he is on screen - perhaps it's something to do with having no resources?

**Comment by pacna** [comment]
fixed in new changes

**Comment by warasilapm** [comment]
thanks @pacna !
