### ISSUE TITLE
mail: figure out how to send a formatted email

### ISSUE THREAD

**Issue by dfirebaugh** [HackRVA/memberdashboard#31]
We can send a plain text email with mailgun.

I was having issues with the formatted email.  It would be nice if we could pass in an html file that's stored in the repo.

Possible email templates:

- notify a member that their access will be revoked
- notify a member that their access has been revoked
- a welcome email
- notification that a resource has been offline for a while

**Comment by Ranthalion** [comment]
- [ ] Enable html send via mailgun API
- [ ] Implement template parsing
- [ ] IP Address changed
- [ ] New member welcome
- [ ] Pending Revokation - Member
- [ ] Pending Revokation - Leadership
- [ ] Resource Offline
- [ ] Access Revoked - Member
- [ ] Access Revoked - Leadership
