### ISSUE TITLE
db: Create a place in the db to store logs

### ISSUE THREAD

**Issue by dfirebaugh** [HackRVA/memberdashboard#68]
Log event are received from the rfid readers in json format
e.g.
```json
{"cmd":"log","type":"access","time":1616946502,"isKnown":"true","access":"Always","username":"Joe Shmo","uid":"23b6234","door":"esp-rfid"}
```

We may want to have some kind of mechanism that rotates the table so that we don't put too much data in.
https://www.postgresql.org/docs/8.2/ddl-partitioning.html

**Comment by pacna** [comment]
This is done
