### ISSUE TITLE
GetMembersWithCredit func does not seem to return anything

### ISSUE THREAD

**Issue by dfirebaugh** [HackRVA/memberdashboard#80]
For some reason this function is returning an empty slice.

???

**Comment by Ranthalion** [comment]
Unable to reproduce.  Working test in PR #86

**Comment by dfirebaugh** [comment]
I think I was seeing errors from the `EvaluateMemberStatus` function.

I added a condition that ignores members with Credited status.
https://github.com/HackRVA/memberdashboard/blob/c0a73b698cba5b7c9e4178762c26a8c22048d633/database/payment.go#L156
